spring:
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306
      username:
      password:
      driver-class-name: com.mysql.jdbc.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: SpringPhysicalNamingStrategy
